version: '3'
services:
  db: &DB
    image: postgres
    ports: 
      - 5432
    volumes:
      - /data/soccer-scorer/develop:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
  testdb:
    <<: *DB
    volumes:
      - /data/soccer-scorer/test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  web:
    build: dev
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - testdb
      - db
