version: '2.1'
services:
  db: 
    image: postgres
    ports: 
      - 5432
    volumes:
      - ./scripts/init-test-user-db.sh:/docker-entrypoint-initdb.d/init-test-user-db.sh
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  web:
    build: .
    command: sh scripts/run-test.sh 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
