# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6016ff9548719087928b611c2dd70f83987ab0049091f2fab03a1643fe5fcd1940b4cf944b81377293a8c0b478556384d4278babda19395f2282ff063a518151

test:
  secret_key_base: 4fc5abc5f15774b46370b2633a987dcd1e8fee348e93c24762df7ac11d0855ab9c696c768332c38aa503efc5e4fb4d041beb3fbc86c066a8e91b32940b518f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
